export const ActionTypes = {
    FETCH_WORKSHOPS_SUCCESS : "FETCH_WORKSHOPS_SUCCESS",
    UPDATE_WORKSHOP_SUCCESS : "UPDATE_WORKSHOP_SUCCESS",
    WORKSHOPS_LOADING : "WORKSHOPS_LOADING",
    CREATE_PRODUCTS_SUCCESS : "CREATE_PRODUCTS_SUCCESS",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS",
    REMOVE_FROM_PRODUCT:"REMOVE_FROM_PRODUCT",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    UPDATE_PRODUCTS_SUCCESS:"UPDATE_PRODUCTS_SUCCESS"


};