export const ActionTypes = {
    //Workshops
    FETCH_WORKSHOPS_SUCCESS : "FETCH_WORKSHOPS_SUCCESS",
    UPDATE_WORKSHOP_SUCCESS : "UPDATE_WORKSHOP_SUCCESS",
    WORKSHOPS_LOADING : "WORKSHOPS_LOADING",
    CREATE_WORKSHOP_SUCCESS:"CREATE_WORKSHOP_SUCCESS",
    FETCH_WORKSHOP_TAGS_SUCCESS:"FETCH_WORKSHOP_TAGS_SUCCESS",
    WORKSHOPS_TAGS_LOADING:"WORKSHOPS_TAGS_LOADING",
    DELETE_WORKSHOPS_SUCCESS:"DELETE_WORKSHOPS_SUCCESS",

    //SuperUsers
    FETCH_SUPERUSERS_SUCCESS : "FETCH_SUPERUSERS_SUCCESS",
    SUPERUSERS_LOADING : "SUPERUSERS_LOADING",
    UPDATE_SUPERUSER_SUCCESS: "UPDATE_SUPERUSER_SUCCESS",
    CREATE_SUPERUSER_SUCCESS: "CREATE_SUPERUSER_SUCCESS",
    DELETE_SUPERUSER_SUCCESS: "DELETE_SUPERUSER_SUCCESS",
    SUPERUSER_LOGIN_SUCCESS: "SUPERUSER_LOGIN_SUCCESS",
    SUPERUSER_LOGIN_FAIL: "SUPERUSER_LOGIN_FAIL",
    SUPERUSER_LOGOUT: "SUPERUSER_LOGOUT",
    SUPERUSER_LOGIN_RESET: "SUPERUSER_LOGIN_RESET",

    //EndUsers
    VALIDATE_ENDUSER_SUCCESS: "VALIDATE_ENDUSER_SUCCESS",

    //News
    FETCH_NEWS_SUCCESS:"FETCH_NEWS_SUCCESS",
    NEWS_LOADING:"NEWS_LOADING",
    UPDATE_NEWS_SUCCESS:"UPDATE_NEWS_SUCCESS",
    CREATE_NEWS_SUCCESS: "CREATE_NEWS_SUCCESS",
    FETCH_NEWS_TAGS_SUCCESS: "FETCH_NEWS_TAGS_SUCCESS",
    DELETE_NEWS_SUCCESS:"DELETE_NEWS_SUCCESS",

    //Research
    FETCH_RESEARCH_SUCCESS:"FETCH_RESEARCH_SUCCESS",
    RESEARCH_LOADING:"RESEARCH_LOADING",
    UPDATE_RESEARCH_SUCCESS:"UPDATE_RESEARCH_SUCCESS",
    SET_RESEARCH_LINK:"SET_RESEARCH_LINK",
    DELETE_RESEARCH_SUCCESS:"DELETE_RESEARCH_SUCCESS",
    CREATE_RESEARCH_SUCCESS:"CREATE_RESEARCH_SUCCESS",

    //Researcher Registration
    RESEARCHER_REGISTER_NEXT: "RESEARCHER_REGISTER_NEXT",

    //Research Paper
    VALIDATE_RESEARCH_PAPER_SUCCESS: "VALIDATE_RESEARCH_PAPER_SUCCESS",
    RESEARCH_PAPER_NEXT: "RESEARCH_PAPER_NEXT",
    
    CREATE_PRODUCTS_SUCCESS : "CREATE_PRODUCTS_SUCCESS",
    ADD_TO_CART : "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CREATE_USER_SUCCESS:"CREATE_USER_SUCCESS"
  
};